### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ricoperdiz** [ricoperdiz/NIRtools#3]
- [ ] Remove .Rproj from package
- [ ] Add package names before functions in nir_pkgs.R
- [ ] Change function `build_NIRdataset` to allow use of dataframe containing parameter specification.
- [ ] Prepare codes for methods of summary and print
- [ ] Prepare a new vignette for pre processing NIR data.
- [ ] Update all vignettes.
- [ ] Add functions to serve as templates for NIR analysis using `caret` and `tidymodels` framework.
- [x] Prepare codes for methods of plot - done in commit 2adf85f.
- [x] Create a class nirdf to allow methods above - done in commit 2adf85f.
- [x] Split vignette NIRtools_tutorial in two, one for an overview of the package with demonstration of all functions, and other with more details of each function.
- [x] Add a R lifecycle badge of EXPERIMENTAL. Check R package __usethis__.
